### ISSUE TITLE
Decrypted strings are not saved?

### ISSUE THREAD

**Issue by koxu1996** [GraxCode/AntiZKM#3]
I run AntiWindow.main() and select ZKM5 :
![image](https://user-images.githubusercontent.com/6506780/29506392-abe3261c-864b-11e7-9cff-fba902e144a9.png)
Then I drag [Sample.jar](https://github.com/GraxCode/AntiZKM/files/1237955/Sample.jar.txt) and file `Sample.jar-re.jar` is successfully created, but after opening it in JByteMod I still see encrypted strings:
![image](https://i.snag.gy/Ty0nhF.jpg)

Console output from deobfuscating:
```
Loading: /home/andrew/AntiZKM/Sample.jar (Reading Libraries: true)...
Generating mappings...
Merging target and library mappings...
Completed loading from: /home/andrew/AntiZKM/Sample.jar
Saving...
Done!
```

I checked with debugger and AntiZKM is decrypting strings:
![image](https://i.snag.gy/rSa2j0.jpg)
but they are not in output jar.

**Comment by Eyremba** [comment]
Dude this happens also when the ZKM version is newer than the deobfuscator :P

**Comment by ThisTestUser** [comment]
Try to use the deobfuscator here: https://github.com/java-deobfuscator/deobfuscator
It seems that the ZKM string encryption is not supported here.

**Comment by koxu1996** [comment]
@ThisTestUser I tried that deobfuscator and it was throwing many NullPointer (https://github.com/java-deobfuscator/deobfuscator/issues/14) and StackOverflow exceptions (https://github.com/java-deobfuscator/deobfuscator/issues/73).

**Comment by koxu1996** [comment]
Strings were not replaced because `zkmFieldName` was incorrect. I just uncommented two conditions to make to make it work properly.

BTW after deobfuscation <clinit> contains crypted strings which can be removed.

**Comment by koxu1996** [comment]
After merge it's working fine :+1:
